#! /bin/sh

### BEGIN INIT INFO
# Provides:		tedge-agent
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Thin-edge logfile retriever for Cumulocity
# Description:
#  Thin-edge logfile retriever for Cumulocity
#
### END INIT INFO

set -e

PIDFILE=/run/lock/c8y-log-plugin.pid
DAEMON=/usr/bin/c8y-log-plugin

DAEMON_ARGS=""

export TEDGE_RUN_LOCK_FILES="false"

# /etc/init.d/c8y-log-plugin: start and stop c8y-log-plugin

test -x ${DAEMON} || exit 0

umask 022

. /lib/lsb/init-functions

# Are we running from init?
run_by_init() {
    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
}

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	if init_is_upstart; then
	    exit 1
	fi
	log_daemon_msg "Starting network daemon:" "c8y-log-plugin"
	if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile "${PIDFILE}" --exec "${DAEMON}" -- $DAEMON_ARGS ; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;
  stop)
	if init_is_upstart; then
	    exit 0
	fi
	log_daemon_msg "Stopping network daemon:" "c8y-log-plugin"
	if start-stop-daemon --stop --quiet --oknodo --pidfile "${PIDFILE}"; then
	    log_end_msg 0
	    rm -f "${PIDFILE}"
	else
	    log_end_msg 1
	fi
	;;

  restart)
	if init_is_upstart; then
	    exit 1
	fi
	log_daemon_msg "Restarting network daemon:" "c8y-log-plugin"
	if start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile "${PIDFILE}"; then
	    rm -f "${PIDFILE}"
	fi
	if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile "${PIDFILE}" --exec "${DAEMON}" -- $DAEMON_ARGS ; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
	;;

  status)
	if init_is_upstart; then
	    exit 1
	fi
	status_of_proc -p "${PIDFILE}" "${DAEMON}" "c8y-log-plugin" && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/c8y-log-plugin {start|stop|restart|status}"
	exit 1
esac

exit 0