#!/bin/sh -e
touch "/var/log/mosquitto.log"
DAEMON_USER="root"
LOG_FILE="/var/log/mosquitto.log"
PIDFILE="/run/lock/mosquitto.lock"

mkdir -p /run/lock
chown 1777 /run/lock
touch "$PIDFILE"

if [ -n "$DAEMON_USER" ]; then
    chown "$DAEMON_USER" "$PIDFILE"
    chown "$DAEMON_USER" "/var/log/mosquitto.log"
fi
exec chpst -u "$DAEMON_USER" "/usr/sbin/mosquitto" -c /etc/mosquitto/mosquitto.conf >> "$LOG_FILE" 2>&1
