#!/bin/sh -e
touch "/var/log/tedge-configuration-plugin.log"
DAEMON_USER="root"
LOG_FILE="/var/log/tedge-configuration-plugin.log"
PIDFILE="/run/lock/tedge-configuration-plugin.lock"

mkdir -p /run/lock
chown 1777 /run/lock
touch "$PIDFILE"

if [ -n "$DAEMON_USER" ]; then
    chown "$DAEMON_USER" "$PIDFILE"
    chown "$DAEMON_USER" "/var/log/tedge-configuration-plugin.log"
fi
exec chpst -u "$DAEMON_USER" "/usr/bin/tedge-configuration-plugin"  >> "$LOG_FILE" 2>&1
